services:

  syslogng:
    image: linuxserver/syslog-ng
    container_name: syslogng
    depends_on: 
      - elasticsearch
    networks:
      - elk
    configs:
      - source: syslog_conf
        target: /config/syslog-ng.conf
      - source: syslog_conf # duplicate conf destination in case of entrypoint overwrite
        target: /etc/syslog-ng/syslog-ng.conf
    volumes:
      - common_logs:/logs:rw
      - certs:/config/certs:rw
    entrypoint: ["/usr/sbin/syslog-ng", "-F", "-def", "/etc/syslog-ng/syslog-ng.conf"]


  snort:
    image: dockurr/snort
    container_name: snort
    depends_on: 
      - elasticsearch
    networks:
      - elk


  kibana:
    image: kibana:9.1.3
    container_name: kibana
    depends_on: 
      - elasticsearch
    networks:
      - elk
    ports:
      - "5601:5601"

  elasticsearch:
    image: elasticsearch:9.1.3
    container_name: elasticsearch
    networks:
      - elk
    volumes:
      - certs:/certs:rw

  debian:
    container_name: debian
    build:
      context: ./configs
      dockerfile: dockerfile_debian.txt
    ports:
      - "80:80"
      - "2222:22"
    volumes:
      - common_logs:/var/log
    restart: unless-stopped
    networks:
      - elk
    cap_add:
      - NET_ADMIN
      - NET_RAW
    configs:
      - source: suricata_conf
        target: /etc/suricata/suricata.yaml
      - source: suricata_rules
        target: /etc/suricata/rules/suricata.rules
      - source: index_php
        target: /var/www/html/index.php
      - source: login_php
        target: /var/www/html/login.php
      - source: admin_php
        target: /var/www/html/admin.php
      - source: sha256malware
        target: /etc/suricata/rules/sha256malware.list

configs:
  syslog_conf:
    file: ./configs/syslog-ng.conf
  suricata_conf:
    file: ./configs/suricata.yaml
  suricata_rules:
    file: ./configs/suricata.rules
  index_php:
    file: ./configs/index.php
  admin_php:
    file: ./configs/admin.php
  login_php:
    file: ./configs/login.php
  sha256malware:
    file: ./configs/sha256malware.list


networks:
  elk:
    driver: bridge

volumes:
  common_logs:
  certs:


