FROM debian:bookworm
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends openssh-server apache2 php tcpdump wget procps nano suricata suricata-update iputils-ping vim tree curl net-tools iproute2 sudo jq && \
    rm -rf /var/lib/apt/lists/*

RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf

RUN touch /var/log/auth.log && \
    chown root:root /var/log/auth.log && \
    chmod 600 /var/log/auth.log

RUN rm /var/www/html/index.html
RUN touch /var/www/html/flag.txt
RUN echo 'flag{c0mm@nd_inject!0n_m@ster}' > /var/www/html/flag.txt

RUN mkdir -p /var/run/sshd && \
    echo 'root:root' | chpasswd && \
    sed -i 's/^#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config || true && \
    sed -i '/^PermitRootLogin/ s/.*/PermitRootLogin yes/' /etc/ssh/sshd_config || true

EXPOSE 80 22

CMD ["/bin/bash","-lc","truncate -s 0 /var/log/suricata/* || true & truncate -s 0 var/log/apache2/* || true & truncate -s 0 /var/log/auth.log || true & rm -rf /var/log/suricata/filestore || true & /usr/sbin/sshd -D -E /var/log/auth.log & /bin/suricata -c /etc/suricata/suricata.yaml -vvv -i eth0 & exec apache2ctl -D FOREGROUND"]